version: '3'
services:
  db:
    image: postgres:17.5
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: prestamos_v2
    volumes:
      - ./postgres:/var/lib/postgresql/data
